"""empty message

Revision ID: 15196fdcb27b
Revises: 155fd3c0b64c
Create Date: 2023-04-25 19:42:37.799418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15196fdcb27b'
down_revision = '155fd3c0b64c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body_html', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('body_html')

    # ### end Alembic commands ###
