"""empty message

Revision ID: 938f99a41af3
Revises: 931ca6753bee
Create Date: 2023-04-04 17:16:13.568180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '938f99a41af3'
down_revision = '931ca6753bee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
